import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Logo from "../public/logo.ico";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M Magazine",
  description: "Generated by create next app",
  icons: {
    icon: Logo.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Header />
          <div className="mt-44">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
